-name: durecdial
-train_data_path: data/rec_data/DuRecDial/data/en_train.txt
-dev_data_path: data/rec_data/DuRecDial/data/en_dev.txt
-test_data_path: data/rec_data/DuRecDial/data/en_test.txt
-n_goal: 14
-n_topics: 646